import unreal
ikr_target = unreal.EditorAssetLibrary.load_asset("/Game/Retargeting/IK_AutoGeneratedTarget")
ikr_source = unreal.EditorAssetLibrary.load_asset("/Game/Retargeting/IK_AutoGeneratedSource")

ctrl_cls = unreal.IKRigController
methods = [m for m in dir(ctrl_cls) if not m.startswith('_')]
unreal.log(f"CONTROLLER_METHODS: {methods}")

try:
    ctrl = unreal.IKRigController.get_controller(ikr_target)
    unreal.log(f"target controller: {ctrl}")
    for m in ["get_skeletal_mesh", "get_preview_mesh"]:
        if hasattr(ctrl, m):
            v = getattr(ctrl, m)()
            unreal.log(f"  {m}() -> {v.get_path_name() if v else None}")
except Exception as e:
    unreal.log(f"ERROR: {e}")
