import unreal
ikr_source = unreal.EditorAssetLibrary.load_asset("/Game/Retargeting/IK_AutoGeneratedSource")
ctrl = unreal.IKRigController.get_controller(ikr_source)
mesh = ctrl.get_skeletal_mesh()
unreal.log(f"SOURCE_MESH: {mesh.get_path_name() if mesh else None}")
