import unreal

registry = unreal.AssetRegistryHelpers.get_asset_registry()
all_anims = registry.get_assets_by_path("/Game/Characters/UEFN_Mannequin/Animations", recursive=True)

targets = []
for a in all_anims:
    cls = str(a.asset_class_path.asset_name)
    name = str(a.asset_name)
    if cls == "AnimSequence" and not name.endswith("_Retargeted"):
        targets.append(a)

unreal.log(f"TOTAL_TO_RETARGET: {len(targets)}")

source_mesh = unreal.EditorAssetLibrary.load_asset("/Game/Characters/UEFN_Mannequin/Meshes/SKM_UEFN_Mannequin")
target_mesh = unreal.EditorAssetLibrary.load_asset("/Game/Blueprints/Character/Characters/Mannequins/Meshes/SKM_Manny_Simple")
ik_retarget_asset = unreal.EditorAssetLibrary.load_asset("/Game/Retargeting/RTG_AutoGenerated")

unreal.log(f"source_mesh loaded: {source_mesh is not None}, target_mesh loaded: {target_mesh is not None}, retargeter loaded: {ik_retarget_asset is not None}")

result = unreal.IKRetargetBatchOperation.duplicate_and_retarget(
    targets,
    source_mesh,
    target_mesh,
    ik_retarget_asset,
    search="",
    replace="",
    prefix="",
    suffix="_Retargeted",
    include_referenced_assets=False,
    overwrite_existing_files=True,
)
unreal.log(f"RESULT_COUNT: {len(result)}")
unreal.log("Saving all dirty packages...")
unreal.EditorAssetLibrary.save_directory("/Game/Characters/UEFN_Mannequin/Animations", only_if_is_dirty=True, recursive=True)
unreal.log("BATCH_RETARGET_DONE")
